{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "generic-app.namespace" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
    {{- if .Values.namespace.istioInjection }}
    istio-injection: {{ .Values.namespace.istioInjection }}
    {{- end }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
